# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Matt Saunders - UX Designer for Agile Teams
email: matt@webbymatt.co.uk
description: > # this means to ignore newlines until "baseurl:"
  I'm a UX and UI designer in Leeds, Yorkshire, offering my services to agencies and software development teams across the UK
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000/" # the base hostname & protocol for your site
twitter_username: matt5409
github_username:  studioraygun

# Build settings
markdown: kramdown
